name: Tests
image: ubuntu:latest

before_install:
  - apt update && apt install -y wget
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
  - nvm install $NODE_VERSION
  - npm i -g yarn

install:
  - yarn --frozen-lockfile --non-interactive --silent --ignore-scripts

script:
  - yarn test-ci